### ISSUE TITLE
有关模型的一些问题

### ISSUE THREAD

**Issue by 424358225** [xxzl0130/ProgrammingExperience#1]
您好，请问您的mdl  和 plan 的xml文件是如何生成的？

**Comment by xxzl0130** [comment]
参考官方的示例，手动编写的

**Comment by 424358225** [comment]
非常感谢，想学习一下QSLider控制关节部分的代码，不知您是否方便贴一下代码或者思路，卡在这里很久了

**Comment by xxzl0130** [comment]
这个很简单啊，槽接过来Slider的值改变信号，把值给关节更新过去就好了  
当然，所有关节的值是要有个记录保存的

**Comment by 424358225** [comment]
就是这里，把MDL的模型映射到SG场景里么？

**Comment by 424358225** [comment]
这里怎么映射的我就没搞明白了
